#!/bin/bash
password=123456
rpm -q expect &>/dev/null
if [ $? -ne 0 ]; then
       echo “install expect......”
       yum install -y expect > /dev/null
fi
if [ ! -f ~/.ssh/id_rsa ]; then
     echo “install ssh-keygen......”
     ssh-keygen -p “ ” -f ~/.ssh/id_rsa >/dev/null
fi
for i in {2..254}
do
     {
          ip=192.168.122.$i
          ping -c1 -W1 $ip &>/dev/null
          if [ $? -eq 0 ]; then 
             echo “$ip” >> ip.txt
             /usr/bin/expect <<-EOF
             set timeout 10
             spawn ssh-copy-id $ip
             expect {
                    “yes/no” { send “yes\r”; exp_continue }
                    “password:" { send “$password\r” }
             }
             expect eof
             EOF
          fi
     }&
done
wait
echo "finish"
