#!/bin/bash
password=123456
while [ $# != 0 ]
do
    num=$1
    cd /app/sftp
    mkdir $num
    useradd $num  -s /sbin/nologin -d /app/sftp/$num -g 501
    echo $password | passwd --stdin $num
    chmod 755 $num
    chown root.root $num
    cd $num
    mkdir check
    chown -R $num.root check
    passwd -x 9999 $num
    sed -i '$a\Match user  '"$num"'\n  ChrootDirectory /app/sftp/'"$num"'\n  ForceCommand internal-sftp' /etc/ssh/sshd_config
    shift
done
/etc/init.d/sshd restart
cksum /etc/passwd
